# Generated by Django 4.0.5 on 2022-07-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
